### PR TITLE
Replace spaces in outcome column with underscores

### LINKED ISSUE #244: Class strings cannot contain spaces in the outcome columns [JOSS review]
I also encountered a bug when running `run_ml()` on a dataset with categorical classes containing spaces in the label column. The classes that caused errors are `"progressive supranuclear palsy"` and `"pathological aging"`. I can mitigate the bug by replacing `" "` with `"_"`, to transform to labels `"progressive_supranuclear_palsy"` and `"pathological_aging"`.

Below are the codes to reproduce the bug.

`amp_data_preproc <- preprocess_data(amp_ad_geneexp_dx, 'dx')$dat_transformed
`
> Using 'dx' as the outcome column.
Removed 1388/1917 (72.4%) of samples because of missing outcome value (NA).

`result_amp <- run_ml(amp_data_preproc, 'glmnet')
`
> Using 'dx' as the outcome column.
Error: At least one of the class levels is not a valid R variable name; This will cause errors when class probabilities are generated because the variables names will be converted to  Alzheimer.Disease, control, pathological.aging, progressive.supranuclear.palsy . Please use factor levels that can be used as valid R variable names  (see ?make.names for help).

It is expected that spaces can occur in the class labels data, or that `preprocess_data()` would automatically prepare the outcomes label.

### PR DESCRIPTION
**Pull request by kelly-sovacool**
Required for compatibility with `caret::createDataPartition()` used in `run_ml()`.

## Issues
- Resolves #244.

## Change(s) made
- New function `replace_spaces()` used in `preprocess_data()` to modify the outcome column.
- Updated docs to mention the change.

## Checklist
- [x] Update `NEWS.md` if this includes any user-facing changes. ~Strikethrough~ if not applicable.
- [x] The check workflow succeeds on your most recent commit.

### CODE REVIEW

File: R/utils.R [hunk 1]
```diff
@@ -131,3 +131,23 @@ select_apply <- function(fun = "apply") {
...
+#'
+#' @examples
+#' dat <- data.frame(
+#'   dx = c("outcome 1", "outcome 2", "outcome 1"),
+#'   a = 1:3, b = c(5, 7, 1)
+#' )
+#' dat$dx <- replace_spaces(dat$dx)
+#' dat
+replace_spaces <- function(x, new_char = "_") {
+  gsub(" ", new_char, x)
```
Comment (zenalapp) [inline R/utils.R:152]: Will this work if there are tabs or some other sort of white space? Not sure why there would be, but just thinking of how it could break.

**Review by zenalapp — APPROVED** [review]
Going to look over the correlation pr next.

File: R/utils.R (hunk 1 above)
Comment (kelly-sovacool) [reply R/utils.R:152]: When reading a csv file containing tabs, `read.csv` and `readr::read_csv` replace the tab character with `\t`, so it's no longer whitespace once parsed into a character vector. e.g. an outcome labelled "a    disease" (imagine that whitespace is a literal tab char) would become "a\tdisease" when parsed.
